### ISSUE TITLE
WinError 2 - File not found

### ISSUE THREAD

**Issue by Norrox** [JoshParnell/ltheory-old#2]
First issue, don't know if it's my python install that's hate me or what :P
![Skärmbild 2022-07-29 190530](https://user-images.githubusercontent.com/13393087/181809475-70eee58c-1ecd-4d24-810d-f931ce98c706.png)

**Comment by GalaxyCr8r** [comment]
Someone on Limit Theory Redux discord had some luck using Powershell

**Comment by Norrox** [comment]
Yeah, got it to work, forgot to add cmake to path :)
